language: ruby

services:
  - docker

before_install:
#  - sudo apt-get update
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get install sshpass
  - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts

script:
  - docker build -t jkostov/notenic-notifications -f Dockerfile.prod .
  - docker tag jkostov/notenic-notifications:latest jkostov/notenic-notifications:$TRAVIS_BUILD_NUMBER
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker login
  - docker push jkostov/notenic-notifications:latest
  - docker push jkostov/notenic-notifications:$TRAVIS_BUILD_NUMBER

after_success:
  - sh ./bin/travis-deploy.sh
